import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet, ScrollView, ActivityIndicator, TouchableOpacity } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { analysisAPI } from '../api/client';
import Colors from '../theme/colors';
import { Typography, Spacing, Radius, Shadows } from '../theme/typography';
import LottieView from 'lottie-react-native';

export default function AISuggestionsScreen({ navigation }) {
  const [insights, setInsights] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchInsights();
  }, []);

  const fetchInsights = async () => {
    try {
      setLoading(true);
      setError(null);
      const res = await analysisAPI.getAIInsights();
      if (res.data && res.data.success) {
        setInsights(Array.isArray(res.data.data) ? res.data.data : [res.data.data]);
      } else {
        setError('Failed to load insights.');
      }
    } catch (err) {
      console.error(err);
      setError('An error occurred while fetching insights.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <View style={styles.container}>
      <LinearGradient colors={[Colors.primarySoft, Colors.background]} style={styles.header}>
        <TouchableOpacity style={styles.backBtn} onPress={() => navigation.goBack()}>
          <Ionicons name="arrow-back" size={24} color={Colors.text} />
        </TouchableOpacity>
        <Text style={styles.title}>AI Suggestions</Text>
      </LinearGradient>
      
      <ScrollView contentContainerStyle={styles.content}>
        {loading ? (
          <View style={styles.centerBox}>
            <ActivityIndicator size="large" color={Colors.primary} />
            <Text style={styles.loadingText}>Analyzing your recent habits...</Text>
          </View>
        ) : error ? (
          <View style={styles.centerBox}>
            <Ionicons name="alert-circle-outline" size={48} color={Colors.riskCritical} />
            <Text style={styles.errorText}>{error}</Text>
            <TouchableOpacity style={styles.retryBtn} onPress={fetchInsights}>
              <Text style={styles.retryText}>Retry</Text>
            </TouchableOpacity>
          </View>
        ) : (
          <View>
            <View style={styles.introBox}>
              <LottieView
                source={require('../../assets/animations/meditation.json')}
                autoPlay
                loop
                style={{ width: 80, height: 80 }}
              />
              <Text style={styles.introText}>Here are some personalized suggestions based on your recent health logs, generated by Gemini AI.</Text>
            </View>

            {insights.map((insight, idx) => (
              <View key={idx} style={styles.card}>
                <View style={styles.cardHeader}>
                  <Ionicons name="sparkles" size={24} color={Colors.accent} />
                  <Text style={styles.cardTitle}>Insight #{idx + 1}</Text>
                </View>
                <Text style={styles.cardContent}>{insight}</Text>
              </View>
            ))}
          </View>
        )}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: {
    paddingTop: 60,
    paddingBottom: Spacing.xl,
    paddingHorizontal: Spacing.xxl,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomLeftRadius: Radius.xl,
    borderBottomRightRadius: Radius.xl,
  },
  backBtn: { marginRight: Spacing.md },
  title: { ...Typography.h1, color: Colors.text },
  content: { padding: Spacing.xxl, paddingBottom: 100 },
  centerBox: { flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 100 },
  loadingText: { ...Typography.body, color: Colors.textSecondary, marginTop: Spacing.lg },
  errorText: { ...Typography.body, color: Colors.textSecondary, marginTop: Spacing.md, textAlign: 'center' },
  retryBtn: { marginTop: Spacing.lg, paddingVertical: Spacing.sm, paddingHorizontal: Spacing.xl, backgroundColor: Colors.primary, borderRadius: Radius.round },
  retryText: { color: '#fff', ...Typography.body, fontWeight: 'bold' },
  introBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.surface, padding: Spacing.lg, borderRadius: Radius.lg, marginBottom: Spacing.xl, ...Shadows.small },
  introText: { flex: 1, ...Typography.bodySmall, color: Colors.textSecondary, marginLeft: Spacing.md },
  card: { backgroundColor: Colors.surface, borderRadius: Radius.lg, padding: Spacing.xl, marginBottom: Spacing.lg, ...Shadows.medium },
  cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: Spacing.md },
  cardTitle: { ...Typography.h3, color: Colors.text, marginLeft: Spacing.sm },
  cardContent: { ...Typography.body, color: Colors.textSecondary, lineHeight: 24 },
});
